spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ${APP_NAME}
server:
  port: ${SERVER_PORT:0}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}